### ISSUE TITLE
UTC offset data type ERROR

### ISSUE THREAD

**Issue by k0T0z** [aquilax/sunrise-sunset-calc#9]
I think UTC offset must be of type double not an integer, please fix this!!

getSunriseSunset(60.0, 60.0, =====> here must be of type double <===== ,
DateTime.now());

**Comment by k0T0z** [comment]
Example:
countries like 'Afghanistan' has 'UTC+04:30' and many others, please have a look at this

**Comment by aquilax** [comment]
Good catch. Looks like Duration will be a better fit than double.

**Comment by aquilax** [comment]
Version `3.0.0`, which uses `Duration` is now published.

**Comment by k0T0z** [comment]
thanks a lot @aquilax

**Comment by k0T0z** [comment]
how can you handle if the offset is -ve or +ve then? @aquilax 
I made changes to the files and it worked (with double as a data type for UTC offset)
we can't send +ve or -ve offset with Duration
countries like 'Anguilla' has 'UTC-04:00'

**Comment by aquilax** [comment]
Duration can be negative e.g. `print(Duration(hours: -3, minutes: -30));` but in this case you should be able to get the right duration from [timeZoneOffset](https://api.dart.dev/stable/2.17.5/dart-core/DateTime/timeZoneOffset.html)

**Comment by k0T0z** [comment]
cool
